### PR TITLE
corrected grammar and spelling. 

### PR DESCRIPTION
**Pull request by chrisbare**
reworded a few things to improve clarity based on following the process myself.

### CODE REVIEW

**Comment by Superbelko** [comment]
Sorry for late response. For some reason notification was off for me, I'll review and merge this shortly.

**Comment by Superbelko** [comment]
Thanks for feedback and the fixes.
As a non-native speaker it is hard for me to maintain proper wording when communicate with people who has different levels of language proficiency, as a result you might such stupid mistakes like singular/plural mismatch, mixing up present/past forms, etc...

Thanks again, I hope this tutorial was helpful.

**Comment by chrisbare** [comment]
Hey, glad to help. Would it make sense to combine the wiki with the godot-dlang/README.md somehow? It seems like there's a good amount of overlap.
Also, is there any documentation on the struct vs class option? If not, I could write up something once I understand it.

**Comment by Superbelko** [comment]
It might make sense to refine the main readme, but this guide goes into more details, and a readme is here basically for cases such as _"I already know how to do that, just don't remember how to do it exactly"_ or _"whatever, just show me how to use it"_.
These extra details won't be as useful, but the links for an in depth explanation might do.

The difference of using struct vs classes mostly is a D limitations itself, here is a short list of key features(?):
- Using `GodotScript` wrapper when inheriting Godot base classes is not strictly needed with classes version, but to make your code more compatible it is better to add it
- Structs version is a bit more easy on the programmer and often don't need an explicit `override` keyword unlike classes, though adding it will probably work in both cases
- From the user code point of view there shouldn't be any difference between the two

Now of course the performance difference is unknown, in theory modern hardware might favor using pointers(classes version) rather than IDs but without profiling code and cache performance it is impossible to tell which one is faster.

There could be more quirks on using classes with hot reload but that's another issue.

**Pull request merged**
